version: "3"
services:
  nats:
    image: nats:2.10-alpine
    container_name: nats
    restart: always
    ports:
      - "4222:4222" # client port
      - "6222:6222" # cluster port
      - "8222:8222" # monitoring port
    volumes:
      - nats:/data

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=duke
      - POSTGRES_PASSWORD=password
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
  nats:
    driver: local
