apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-wild-server
  labels:
    app: api-wild-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-wild-server
  template:
    metadata:
      labels:
        app: api-wild-server
    spec:
      containers:
        - name: api-wild-server
          image: "me-west1-docker.pkg.dev/gcp-etigcp-nprd-12855/wild-tag/server:{{ .Values.core.imageTag }}"
          ports:
            - containerPort: 8080
          command:
          - "java"
          - "-Xmx512m"
          - "-jar"
          - "wild-tag-latest.jar"
          - "applications.Application"
          envFrom:
            - configMapRef:
                name: wild-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1G"
              cpu: "1"
          imagePullPolicy: IfNotPresent

      imagePullSecrets:
        - name: regcred
