apiVersion: v1
kind: Service
metadata:
  name: api-wild-server
  labels:
    app: api-wild-server
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http-api-wild-server
  selector:
    app: api-wild-server
