apiVersion: v1
kind: ConfigMap
metadata:
  name: wild-config
  labels:
    app: wild-config
data:
  spring.datasource.url: "jdbc:postgresql://wild-postgres:5432/wildtag"
  spring.datasource.username: "wildtag"
  serverUrl: "{{ .Values.global.serverUrl }}"
  job.nats.uri: "nats-wild:4222"