name: CI

on:
  workflow_call:
    secrets:
      GCP_SERVICE_ACCOUNT_KEY:
        description: 'GCP Service Account Key'
        required: true

jobs:
  build-server-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Log in to GCR
        uses: docker/login-action@v2
        with:
          registry: me-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set outputs
        id: gitSha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ${{ github.workspace }}/deployment/docker/server.Dockerfile
          tags: me-west1-docker.pkg.dev/gcp-etigcp-nprd-12855/wild-tag/server:${{ steps.gitSha.outputs.sha_short }}
          platforms: linux/amd64

  build-ui-and-push:
    runs-on: ubuntu-latest

    env:
      RECORD_SUFFIX: ${{ vars.RECORD_SUFFIX }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Log in to GCR
        uses: docker/login-action@v2
        with:
          registry: me-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: discover SHA
        id: gitSha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ${{ github.workspace }}/deployment/docker/ui.Dockerfile
          tags: me-west1-docker.pkg.dev/gcp-etigcp-nprd-12855/wild-tag/ui:${{ steps.gitSha.outputs.sha_short }}
          platforms: linux/amd64
